"""initial_schema

Revision ID: 4f99d55923c7
Revises: 
Create Date: 2026-09-17 10:48:16.290500+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f99d55923c7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_id'), 'teams', ['id'], unique=False)
    op.create_index(op.f('ix_teams_name'), 'teams', ['name'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('auth_provider', sa.Enum('PASSWORD', 'GOOGLE', name='auth_provider_type'), nullable=False),
    sa.Column('oauth_subject_id', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('REQUESTER', 'OPERATOR', 'TEAM_LEAD', 'MANAGER', 'ADMINISTRATOR', 'APPROVER', 'KNOWLEDGE_OWNER', 'SERVICE_OWNER', 'AUDITOR', name='user_role'), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('site', sa.String(length=100), nullable=True),
    sa.Column('availability_status', sa.Enum('AVAILABLE', 'AWAY', 'OFFLINE', name='availability_status'), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_oauth_subject_id'), 'users', ['oauth_subject_id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_foreign_key('fk_teams_lead_id_users', 'teams', 'users', ['lead_id'], ['id'], ondelete='SET NULL')
    op.create_table('audit_logs',
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.String(length=100), nullable=False),
    sa.Column('before_value', sa.JSON(), nullable=True),
    sa.Column('after_value', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_target_id'), 'audit_logs', ['target_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_target_type'), 'audit_logs', ['target_type'], unique=False)
    op.create_table('cases',
    sa.Column('reference_number', sa.String(length=50), nullable=False),
    sa.Column('type', sa.Enum('INCIDENT', 'SERVICE_REQUEST', 'PROBLEM', 'CHANGE', name='case_type'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'NEW', 'IN_ASSESSMENT', 'ASSIGNED', 'AWAITING_REQUESTER', 'AWAITING_APPROVAL', 'PENDING', 'RESOLVED', 'CLOSED', 'CANCELLED', name='case_status'), nullable=False),
    sa.Column('priority', sa.Enum('P1_CRITICAL', 'P2_HIGH', 'P3_MEDIUM', 'P4_LOW', name='priority_level'), nullable=False),
    sa.Column('requester_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('site', sa.String(length=100), nullable=True),
    sa.Column('service_id', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_id'), 'cases', ['id'], unique=False)
    op.create_index(op.f('ix_cases_priority'), 'cases', ['priority'], unique=False)
    op.create_index(op.f('ix_cases_reference_number'), 'cases', ['reference_number'], unique=True)
    op.create_index(op.f('ix_cases_status'), 'cases', ['status'], unique=False)
    op.create_index(op.f('ix_cases_type'), 'cases', ['type'], unique=False)
    op.create_table('ai_triage_results',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('suggested_category', sa.String(length=100), nullable=False),
    sa.Column('suggested_severity', sa.String(length=50), nullable=False),
    sa.Column('suggested_priority', sa.String(length=20), nullable=False),
    sa.Column('confidence_level', sa.Enum('LOW', 'MODERATE', 'HIGH', name='confidence_level'), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('supporting_factors', sa.JSON(), nullable=False),
    sa.Column('missing_info', sa.JSON(), nullable=False),
    sa.Column('suggested_team', sa.String(length=100), nullable=True),
    sa.Column('recommended_next_action', sa.String(length=255), nullable=True),
    sa.Column('related_case_ids', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_index(op.f('ix_ai_triage_results_id'), 'ai_triage_results', ['id'], unique=False)
    op.create_table('attachments',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_path')
    )
    op.create_index(op.f('ix_attachments_case_id'), 'attachments', ['case_id'], unique=False)
    op.create_index(op.f('ix_attachments_id'), 'attachments', ['id'], unique=False)
    op.create_table('case_relationships',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('related_case_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.Enum('RELATED_TO', 'DUPLICATE_OF', 'PART_OF_MAJOR_INCIDENT', name='relationship_type'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_relationships_case_id'), 'case_relationships', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_relationships_id'), 'case_relationships', ['id'], unique=False)
    op.create_index(op.f('ix_case_relationships_related_case_id'), 'case_relationships', ['related_case_id'], unique=False)
    op.create_table('case_risk_assessments',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MODERATE', 'HIGH', 'CRITICAL', name='risk_level'), nullable=False),
    sa.Column('signals', sa.JSON(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_index(op.f('ix_case_risk_assessments_id'), 'case_risk_assessments', ['id'], unique=False)
    op.create_table('case_summaries',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('last_source_message_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_index(op.f('ix_case_summaries_id'), 'case_summaries', ['id'], unique=False)
    op.create_table('escalation_events',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('trigger_reason', sa.Enum('APPROACHING_DEADLINE', 'MISSED_DEADLINE', 'HIGH_RISK', 'REPEATED_REOPEN', 'OPERATOR_REQUESTED', name='escalation_reason'), nullable=False),
    sa.Column('escalated_to', sa.String(length=100), nullable=False),
    sa.Column('escalated_by', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'ACKNOWLEDGED', 'RESOLVED', name='escalation_status'), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['escalated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_escalation_events_case_id'), 'escalation_events', ['case_id'], unique=False)
    op.create_index(op.f('ix_escalation_events_id'), 'escalation_events', ['id'], unique=False)
    op.create_table('knowledge_articles',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('state', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='article_state'), nullable=False),
    sa.Column('review_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_case_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_case_id'], ['cases.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_articles_category'), 'knowledge_articles', ['category'], unique=False)
    op.create_index(op.f('ix_knowledge_articles_id'), 'knowledge_articles', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_articles_title'), 'knowledge_articles', ['title'], unique=False)
    op.create_table('messages',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('visibility', sa.Enum('REQUESTER_VISIBLE', 'INTERNAL_ONLY', name='message_visibility'), nullable=False),
    sa.Column('ai_generated', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_case_id'), 'messages', ['case_id'], unique=False)
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_index(op.f('ix_messages_visibility'), 'messages', ['visibility'], unique=False)
    op.create_table('slas',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('target_response_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('target_resolve_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('first_responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response_breached', sa.Boolean(), nullable=False),
    sa.Column('resolve_breached', sa.Boolean(), nullable=False),
    sa.Column('paused_reason', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_index(op.f('ix_slas_id'), 'slas', ['id'], unique=False)
    op.create_table('communication_drafts',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('draft_type', sa.Enum('INFO_REQUEST', 'PROGRESS_UPDATE', 'RESOLUTION', 'ESCALATION_SUMMARY', name='draft_type'), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'DISCARDED', name='draft_status'), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('sent_message_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sent_message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_communication_drafts_case_id'), 'communication_drafts', ['case_id'], unique=False)
    op.create_index(op.f('ix_communication_drafts_id'), 'communication_drafts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_communication_drafts_id'), table_name='communication_drafts')
    op.drop_index(op.f('ix_communication_drafts_case_id'), table_name='communication_drafts')
    op.drop_table('communication_drafts')
    op.drop_index(op.f('ix_slas_id'), table_name='slas')
    op.drop_table('slas')
    op.drop_index(op.f('ix_messages_visibility'), table_name='messages')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_case_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_knowledge_articles_title'), table_name='knowledge_articles')
    op.drop_index(op.f('ix_knowledge_articles_id'), table_name='knowledge_articles')
    op.drop_index(op.f('ix_knowledge_articles_category'), table_name='knowledge_articles')
    op.drop_table('knowledge_articles')
    op.drop_index(op.f('ix_escalation_events_id'), table_name='escalation_events')
    op.drop_index(op.f('ix_escalation_events_case_id'), table_name='escalation_events')
    op.drop_table('escalation_events')
    op.drop_index(op.f('ix_case_summaries_id'), table_name='case_summaries')
    op.drop_table('case_summaries')
    op.drop_index(op.f('ix_case_risk_assessments_id'), table_name='case_risk_assessments')
    op.drop_table('case_risk_assessments')
    op.drop_index(op.f('ix_case_relationships_related_case_id'), table_name='case_relationships')
    op.drop_index(op.f('ix_case_relationships_id'), table_name='case_relationships')
    op.drop_index(op.f('ix_case_relationships_case_id'), table_name='case_relationships')
    op.drop_table('case_relationships')
    op.drop_index(op.f('ix_attachments_id'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_case_id'), table_name='attachments')
    op.drop_table('attachments')
    op.drop_index(op.f('ix_ai_triage_results_id'), table_name='ai_triage_results')
    op.drop_table('ai_triage_results')
    op.drop_index(op.f('ix_cases_type'), table_name='cases')
    op.drop_index(op.f('ix_cases_status'), table_name='cases')
    op.drop_index(op.f('ix_cases_reference_number'), table_name='cases')
    op.drop_index(op.f('ix_cases_priority'), table_name='cases')
    op.drop_index(op.f('ix_cases_id'), table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_audit_logs_target_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_target_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_oauth_subject_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_teams_name'), table_name='teams')
    op.drop_index(op.f('ix_teams_id'), table_name='teams')
    op.drop_constraint('fk_teams_lead_id_users', 'teams', type_='foreignkey')
    op.drop_table('teams')
    # ### end Alembic commands ###
