from datetime import datetime
from typing import Optional, Union
from uuid import UUID
from pydantic import BaseModel, Field
from backend.models.enums import MessageVisibility
from backend.schemas.auth import UserResponse


class MessageCreateRequest(BaseModel):
    body: str = Field(..., min_length=1, max_length=5000, description="Message text content")
    visibility: MessageVisibility = Field(
        default=MessageVisibility.REQUESTER_VISIBLE,
        description="requester_visible for general communication; internal_only for staff notes",
    )
    ai_generated: bool = Field(default=False, description="Whether drafted or generated by AI")


class MessageResponse(BaseModel):
    id: Union[UUID, str]
    case_id: Union[UUID, str]
    author_id: Optional[Union[UUID, str]]
    body: str
    visibility: MessageVisibility
    ai_generated: bool
    created_at: datetime
    author: Optional[UserResponse] = None

    class Config:
        from_attributes = True
